//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestPipePowerPonit.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestPipePowerPonit.Languages.LoginFormStrings", typeof(LoginFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmail.
        /// </summary>
        internal static string ForgotPasswordForm_EmailPlaceholder_EN {
            get {
                return ResourceManager.GetString("ForgotPasswordForm_EmailPlaceholder_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmail.
        /// </summary>
        internal static string ForgotPasswordForm_EmailPlaceholder_VI {
            get {
                return ResourceManager.GetString("ForgotPasswordForm_EmailPlaceholder_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Login.
        /// </summary>
        internal static string ForgotPasswordForm_Login_EN {
            get {
                return ResourceManager.GetString("ForgotPasswordForm_Login_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại Đăng nhập.
        /// </summary>
        internal static string ForgotPasswordForm_Login_VI {
            get {
                return ResourceManager.GetString("ForgotPasswordForm_Login_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending OTP....
        /// </summary>
        internal static string ForgotPasswordForm_Sending_EN {
            get {
                return ResourceManager.GetString("ForgotPasswordForm_Sending_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi OTP....
        /// </summary>
        internal static string ForgotPasswordForm_Sending_VI {
            get {
                return ResourceManager.GetString("ForgotPasswordForm_Sending_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send OTP.
        /// </summary>
        internal static string ForgotPasswordForm_SendOtp_EN {
            get {
                return ResourceManager.GetString("ForgotPasswordForm_SendOtp_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi OTP.
        /// </summary>
        internal static string ForgotPasswordForm_SendOtp_VI {
            get {
                return ResourceManager.GetString("ForgotPasswordForm_SendOtp_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPasswordForm_Title_EN {
            get {
                return ResourceManager.GetString("ForgotPasswordForm_Title_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên Mật Khẩu.
        /// </summary>
        internal static string ForgotPasswordForm_Title_VI {
            get {
                return ResourceManager.GetString("ForgotPasswordForm_Title_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginForm_BtnLogin_EN {
            get {
                return ResourceManager.GetString("LoginForm_BtnLogin_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string LoginForm_BtnLogin_VI {
            get {
                return ResourceManager.GetString("LoginForm_BtnLogin_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string LoginForm_ForgotPassword_EN {
            get {
                return ResourceManager.GetString("LoginForm_ForgotPassword_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        internal static string LoginForm_ForgotPassword_VI {
            get {
                return ResourceManager.GetString("LoginForm_ForgotPassword_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue with Google.
        /// </summary>
        internal static string LoginForm_GoogleBtn_EN {
            get {
                return ResourceManager.GetString("LoginForm_GoogleBtn_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục với Google.
        /// </summary>
        internal static string LoginForm_GoogleBtn_VI {
            get {
                return ResourceManager.GetString("LoginForm_GoogleBtn_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Account?.
        /// </summary>
        internal static string LoginForm_NoAccount_EN {
            get {
                return ResourceManager.GetString("LoginForm_NoAccount_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có tài khoản?.
        /// </summary>
        internal static string LoginForm_NoAccount_VI {
            get {
                return ResourceManager.GetString("LoginForm_NoAccount_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string LoginForm_Or_EN {
            get {
                return ResourceManager.GetString("LoginForm_Or_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoặc.
        /// </summary>
        internal static string LoginForm_Or_VI {
            get {
                return ResourceManager.GetString("LoginForm_Or_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string LoginForm_Register_EN {
            get {
                return ResourceManager.GetString("LoginForm_Register_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        internal static string LoginForm_Register_VI {
            get {
                return ResourceManager.GetString("LoginForm_Register_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        internal static string LoginForm_SigningIn_EN {
            get {
                return ResourceManager.GetString("LoginForm_SigningIn_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang đăng nhập....
        /// </summary>
        internal static string LoginForm_SigningIn_VI {
            get {
                return ResourceManager.GetString("LoginForm_SigningIn_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginForm_Title_EN {
            get {
                return ResourceManager.GetString("LoginForm_Title_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string LoginForm_Title_VI {
            get {
                return ResourceManager.GetString("LoginForm_Title_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Google ClientId/Secret is missing in App.config..
        /// </summary>
        internal static string Message_GoogleConfigMissing_EN {
            get {
                return ResourceManager.GetString("Message_GoogleConfigMissing_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Google ClientId/Secret chưa cấu hình trong App.config.
        /// </summary>
        internal static string Message_GoogleConfigMissing_VI {
            get {
                return ResourceManager.GetString("Message_GoogleConfigMissing_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google sign-in successful!.
        /// </summary>
        internal static string Message_GoogleSuccess_EN {
            get {
                return ResourceManager.GetString("Message_GoogleSuccess_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập Google thành công!.
        /// </summary>
        internal static string Message_GoogleSuccess_VI {
            get {
                return ResourceManager.GetString("Message_GoogleSuccess_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed!.
        /// </summary>
        internal static string Message_LoginFailed_EN {
            get {
                return ResourceManager.GetString("Message_LoginFailed_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại!.
        /// </summary>
        internal static string Message_LoginFailed_VI {
            get {
                return ResourceManager.GetString("Message_LoginFailed_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful!.
        /// </summary>
        internal static string Message_LoginSuccess_EN {
            get {
                return ResourceManager.GetString("Message_LoginSuccess_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công!.
        /// </summary>
        internal static string Message_LoginSuccess_VI {
            get {
                return ResourceManager.GetString("Message_LoginSuccess_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reset token received from server..
        /// </summary>
        internal static string Message_NoResetToken_EN {
            get {
                return ResourceManager.GetString("Message_NoResetToken_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không nhận được reset token từ máy chủ..
        /// </summary>
        internal static string Message_NoResetToken_VI {
            get {
                return ResourceManager.GetString("Message_NoResetToken_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resend OTP!.
        /// </summary>
        internal static string Message_OtpResendFailed_EN {
            get {
                return ResourceManager.GetString("Message_OtpResendFailed_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi lại OTP thất bại!.
        /// </summary>
        internal static string Message_OtpResendFailed_VI {
            get {
                return ResourceManager.GetString("Message_OtpResendFailed_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP has been resent to your email..
        /// </summary>
        internal static string Message_OtpResent_EN {
            get {
                return ResourceManager.GetString("Message_OtpResent_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gửi lại OTP vào email của bạn..
        /// </summary>
        internal static string Message_OtpResent_VI {
            get {
                return ResourceManager.GetString("Message_OtpResent_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send OTP!.
        /// </summary>
        internal static string Message_OtpSendFailed_EN {
            get {
                return ResourceManager.GetString("Message_OtpSendFailed_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi OTP thất bại!.
        /// </summary>
        internal static string Message_OtpSendFailed_VI {
            get {
                return ResourceManager.GetString("Message_OtpSendFailed_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP sent successfully!.
        /// </summary>
        internal static string Message_OtpSendSuccess_EN {
            get {
                return ResourceManager.GetString("Message_OtpSendSuccess_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi OTP thành công!.
        /// </summary>
        internal static string Message_OtpSendSuccess_VI {
            get {
                return ResourceManager.GetString("Message_OtpSendSuccess_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP verified successfully!.
        /// </summary>
        internal static string Message_OtpVerified_EN {
            get {
                return ResourceManager.GetString("Message_OtpVerified_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực OTP thành công!.
        /// </summary>
        internal static string Message_OtpVerified_VI {
            get {
                return ResourceManager.GetString("Message_OtpVerified_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify OTP!.
        /// </summary>
        internal static string Message_OtpVerifyFailed_EN {
            get {
                return ResourceManager.GetString("Message_OtpVerifyFailed_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực OTP thất bại!.
        /// </summary>
        internal static string Message_OtpVerifyFailed_VI {
            get {
                return ResourceManager.GetString("Message_OtpVerifyFailed_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration completed successfully!.
        /// </summary>
        internal static string Message_RegistrationSuccess_EN {
            get {
                return ResourceManager.GetString("Message_RegistrationSuccess_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công!.
        /// </summary>
        internal static string Message_RegistrationSuccess_VI {
            get {
                return ResourceManager.GetString("Message_RegistrationSuccess_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset password!.
        /// </summary>
        internal static string Message_ResetPasswordFailed_EN {
            get {
                return ResourceManager.GetString("Message_ResetPasswordFailed_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại mật khẩu thất bại!.
        /// </summary>
        internal static string Message_ResetPasswordFailed_VI {
            get {
                return ResourceManager.GetString("Message_ResetPasswordFailed_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully!.
        /// </summary>
        internal static string Message_ResetPasswordSuccess_EN {
            get {
                return ResourceManager.GetString("Message_ResetPasswordSuccess_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại mật khẩu thành công!.
        /// </summary>
        internal static string Message_ResetPasswordSuccess_VI {
            get {
                return ResourceManager.GetString("Message_ResetPasswordSuccess_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ResetPasswordForm_ConfirmPassword_EN {
            get {
                return ResourceManager.GetString("ResetPasswordForm_ConfirmPassword_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        internal static string ResetPasswordForm_ConfirmPassword_VI {
            get {
                return ResourceManager.GetString("ResetPasswordForm_ConfirmPassword_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Login.
        /// </summary>
        internal static string ResetPasswordForm_Login_EN {
            get {
                return ResourceManager.GetString("ResetPasswordForm_Login_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại Đăng nhập.
        /// </summary>
        internal static string ResetPasswordForm_Login_VI {
            get {
                return ResourceManager.GetString("ResetPasswordForm_Login_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string ResetPasswordForm_NewPassword_EN {
            get {
                return ResourceManager.GetString("ResetPasswordForm_NewPassword_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        internal static string ResetPasswordForm_NewPassword_VI {
            get {
                return ResourceManager.GetString("ResetPasswordForm_NewPassword_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPasswordForm_Reset_EN {
            get {
                return ResourceManager.GetString("ResetPasswordForm_Reset_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại mật khẩu.
        /// </summary>
        internal static string ResetPasswordForm_Reset_VI {
            get {
                return ResourceManager.GetString("ResetPasswordForm_Reset_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting....
        /// </summary>
        internal static string ResetPasswordForm_Resetting_EN {
            get {
                return ResourceManager.GetString("ResetPasswordForm_Resetting_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang đặt lại....
        /// </summary>
        internal static string ResetPasswordForm_Resetting_VI {
            get {
                return ResourceManager.GetString("ResetPasswordForm_Resetting_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPasswordForm_Title_EN {
            get {
                return ResourceManager.GetString("ResetPasswordForm_Title_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt Lại Mật Khẩu.
        /// </summary>
        internal static string ResetPasswordForm_Title_VI {
            get {
                return ResourceManager.GetString("ResetPasswordForm_Title_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        internal static string Title_ConnectionError_EN {
            get {
                return ResourceManager.GetString("Title_ConnectionError_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi Kết Nối.
        /// </summary>
        internal static string Title_ConnectionError_VI {
            get {
                return ResourceManager.GetString("Title_ConnectionError_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Title_Error_EN {
            get {
                return ResourceManager.GetString("Title_Error_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        internal static string Title_Error_VI {
            get {
                return ResourceManager.GetString("Title_Error_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Title_Notification_EN {
            get {
                return ResourceManager.GetString("Title_Notification_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string Title_Notification_VI {
            get {
                return ResourceManager.GetString("Title_Notification_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Title_Success_EN {
            get {
                return ResourceManager.GetString("Title_Success_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành Công.
        /// </summary>
        internal static string Title_Success_VI {
            get {
                return ResourceManager.GetString("Title_Success_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string Title_ValidationError_EN {
            get {
                return ResourceManager.GetString("Title_ValidationError_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi Kiểm Tra.
        /// </summary>
        internal static string Title_ValidationError_VI {
            get {
                return ResourceManager.GetString("Title_ValidationError_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Required.
        /// </summary>
        internal static string Title_VerificationRequired_EN {
            get {
                return ResourceManager.GetString("Title_VerificationRequired_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần xác thực.
        /// </summary>
        internal static string Title_VerificationRequired_VI {
            get {
                return ResourceManager.GetString("Title_VerificationRequired_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password..
        /// </summary>
        internal static string Validation_EmptyConfirmPassword_EN {
            get {
                return ResourceManager.GetString("Validation_EmptyConfirmPassword_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xác nhận mật khẩu..
        /// </summary>
        internal static string Validation_EmptyConfirmPassword_VI {
            get {
                return ResourceManager.GetString("Validation_EmptyConfirmPassword_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Email..
        /// </summary>
        internal static string Validation_EmptyEmail_EN {
            get {
                return ResourceManager.GetString("Validation_EmptyEmail_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Email..
        /// </summary>
        internal static string Validation_EmptyEmail_VI {
            get {
                return ResourceManager.GetString("Validation_EmptyEmail_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter OTP code..
        /// </summary>
        internal static string Validation_EmptyOtp_EN {
            get {
                return ResourceManager.GetString("Validation_EmptyOtp_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã OTP..
        /// </summary>
        internal static string Validation_EmptyOtp_VI {
            get {
                return ResourceManager.GetString("Validation_EmptyOtp_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Password..
        /// </summary>
        internal static string Validation_EmptyPassword_EN {
            get {
                return ResourceManager.GetString("Validation_EmptyPassword_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Mật khẩu..
        /// </summary>
        internal static string Validation_EmptyPassword_VI {
            get {
                return ResourceManager.GetString("Validation_EmptyPassword_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        internal static string Validation_InvalidEmail_EN {
            get {
                return ResourceManager.GetString("Validation_InvalidEmail_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng email không hợp lệ..
        /// </summary>
        internal static string Validation_InvalidEmail_VI {
            get {
                return ResourceManager.GetString("Validation_InvalidEmail_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired OTP..
        /// </summary>
        internal static string Validation_InvalidOtp_EN {
            get {
                return ResourceManager.GetString("Validation_InvalidOtp_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP không hợp lệ hoặc đã hết hạn..
        /// </summary>
        internal static string Validation_InvalidOtp_VI {
            get {
                return ResourceManager.GetString("Validation_InvalidOtp_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP must be 6 digits..
        /// </summary>
        internal static string Validation_InvalidOtpLength_EN {
            get {
                return ResourceManager.GetString("Validation_InvalidOtpLength_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP phải có 6 số..
        /// </summary>
        internal static string Validation_InvalidOtpLength_VI {
            get {
                return ResourceManager.GetString("Validation_InvalidOtpLength_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string Validation_PasswordMismatch_EN {
            get {
                return ResourceManager.GetString("Validation_PasswordMismatch_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không khớp..
        /// </summary>
        internal static string Validation_PasswordMismatch_VI {
            get {
                return ResourceManager.GetString("Validation_PasswordMismatch_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters..
        /// </summary>
        internal static string Validation_PasswordTooShort_EN {
            get {
                return ResourceManager.GetString("Validation_PasswordTooShort_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu tối thiểu 6 ký tự..
        /// </summary>
        internal static string Validation_PasswordTooShort_VI {
            get {
                return ResourceManager.GetString("Validation_PasswordTooShort_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect credentials. Please try again..
        /// </summary>
        internal static string Validation_WrongCredentials_EN {
            get {
                return ResourceManager.GetString("Validation_WrongCredentials_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai thông tin đăng nhập. Vui lòng thử lại..
        /// </summary>
        internal static string Validation_WrongCredentials_VI {
            get {
                return ResourceManager.GetString("Validation_WrongCredentials_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 6-digit OTP.
        /// </summary>
        internal static string VerifyOtpForm_OtpPlaceholder_EN {
            get {
                return ResourceManager.GetString("VerifyOtpForm_OtpPlaceholder_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã OTP 6 số.
        /// </summary>
        internal static string VerifyOtpForm_OtpPlaceholder_VI {
            get {
                return ResourceManager.GetString("VerifyOtpForm_OtpPlaceholder_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend OTP.
        /// </summary>
        internal static string VerifyOtpForm_Resend_EN {
            get {
                return ResourceManager.GetString("VerifyOtpForm_Resend_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi lại OTP.
        /// </summary>
        internal static string VerifyOtpForm_Resend_VI {
            get {
                return ResourceManager.GetString("VerifyOtpForm_Resend_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        internal static string VerifyOtpForm_Sending_EN {
            get {
                return ResourceManager.GetString("VerifyOtpForm_Sending_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gửi....
        /// </summary>
        internal static string VerifyOtpForm_Sending_VI {
            get {
                return ResourceManager.GetString("VerifyOtpForm_Sending_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify OTP.
        /// </summary>
        internal static string VerifyOtpForm_Title_EN {
            get {
                return ResourceManager.GetString("VerifyOtpForm_Title_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác Thực OTP.
        /// </summary>
        internal static string VerifyOtpForm_Title_VI {
            get {
                return ResourceManager.GetString("VerifyOtpForm_Title_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string VerifyOtpForm_Verify_EN {
            get {
                return ResourceManager.GetString("VerifyOtpForm_Verify_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực.
        /// </summary>
        internal static string VerifyOtpForm_Verify_VI {
            get {
                return ResourceManager.GetString("VerifyOtpForm_Verify_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying....
        /// </summary>
        internal static string VerifyOtpForm_Verifying_EN {
            get {
                return ResourceManager.GetString("VerifyOtpForm_Verifying_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xác thực....
        /// </summary>
        internal static string VerifyOtpForm_Verifying_VI {
            get {
                return ResourceManager.GetString("VerifyOtpForm_Verifying_VI", resourceCulture);
            }
        }
    }
}
