//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestPipePowerPonit.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegisterFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestPipePowerPonit.Languages.RegisterFormStrings", typeof(RegisterFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed!.
        /// </summary>
        internal static string Message_RegisterFailed_EN {
            get {
                return ResourceManager.GetString("Message_RegisterFailed_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thất bại!.
        /// </summary>
        internal static string Message_RegisterFailed_VI {
            get {
                return ResourceManager.GetString("Message_RegisterFailed_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created. Please check email for OTP verification..
        /// </summary>
        internal static string Message_RegisterSuccess_EN {
            get {
                return ResourceManager.GetString("Message_RegisterSuccess_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được tạo. Vui lòng kiểm tra email để xác thực OTP..
        /// </summary>
        internal static string Message_RegisterSuccess_VI {
            get {
                return ResourceManager.GetString("Message_RegisterSuccess_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterForm_BtnRegister_EN {
            get {
                return ResourceManager.GetString("RegisterForm_BtnRegister_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        internal static string RegisterForm_BtnRegister_VI {
            get {
                return ResourceManager.GetString("RegisterForm_BtnRegister_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue with Google.
        /// </summary>
        internal static string RegisterForm_GoogleBtn_EN {
            get {
                return ResourceManager.GetString("RegisterForm_GoogleBtn_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục với Google.
        /// </summary>
        internal static string RegisterForm_GoogleBtn_VI {
            get {
                return ResourceManager.GetString("RegisterForm_GoogleBtn_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province/City.
        /// </summary>
        internal static string RegisterForm_Lbl_Address_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Address_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/Thành phố.
        /// </summary>
        internal static string RegisterForm_Lbl_Address_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Address_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birthday:.
        /// </summary>
        internal static string RegisterForm_Lbl_BirthDate_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_BirthDate_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh:.
        /// </summary>
        internal static string RegisterForm_Lbl_BirthDate_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_BirthDate_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Company:.
        /// </summary>
        internal static string RegisterForm_Lbl_Company_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Company_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty:.
        /// </summary>
        internal static string RegisterForm_Lbl_Company_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Company_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter Password:.
        /// </summary>
        internal static string RegisterForm_Lbl_ConfirmPassword_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_ConfirmPassword_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận Mật khẩu:.
        /// </summary>
        internal static string RegisterForm_Lbl_ConfirmPassword_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_ConfirmPassword_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Level:.
        /// </summary>
        internal static string RegisterForm_Lbl_Edu_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Edu_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình độ học vấn:.
        /// </summary>
        internal static string RegisterForm_Lbl_Edu_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Edu_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmail:.
        /// </summary>
        internal static string RegisterForm_Lbl_Email_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Email_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmail:.
        /// </summary>
        internal static string RegisterForm_Lbl_Email_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Email_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name:.
        /// </summary>
        internal static string RegisterForm_Lbl_FullName_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_FullName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và Tên:.
        /// </summary>
        internal static string RegisterForm_Lbl_FullName_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_FullName_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        internal static string RegisterForm_Lbl_Gender_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Gender_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính:.
        /// </summary>
        internal static string RegisterForm_Lbl_Gender_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Gender_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation:.
        /// </summary>
        internal static string RegisterForm_Lbl_Occupation_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Occupation_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghề nghiệp:.
        /// </summary>
        internal static string RegisterForm_Lbl_Occupation_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Occupation_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string RegisterForm_Lbl_Password_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Password_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu:.
        /// </summary>
        internal static string RegisterForm_Lbl_Password_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Password_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        internal static string RegisterForm_Lbl_Phone_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Phone_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại:.
        /// </summary>
        internal static string RegisterForm_Lbl_Phone_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Lbl_Phone_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login?.
        /// </summary>
        internal static string RegisterForm_Login_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Login_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập?.
        /// </summary>
        internal static string RegisterForm_Login_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Login_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter company.
        /// </summary>
        internal static string RegisterForm_Placeholder_Company_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Placeholder_Company_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập công ty.
        /// </summary>
        internal static string RegisterForm_Placeholder_Company_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Placeholder_Company_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter gmail.
        /// </summary>
        internal static string RegisterForm_Placeholder_Email_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Placeholder_Email_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập gmail.
        /// </summary>
        internal static string RegisterForm_Placeholder_Email_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Placeholder_Email_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter full name.
        /// </summary>
        internal static string RegisterForm_Placeholder_FullName_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Placeholder_FullName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập họ và tên.
        /// </summary>
        internal static string RegisterForm_Placeholder_FullName_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Placeholder_FullName_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter occupation.
        /// </summary>
        internal static string RegisterForm_Placeholder_Occupation_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Placeholder_Occupation_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nghề nghiệp.
        /// </summary>
        internal static string RegisterForm_Placeholder_Occupation_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Placeholder_Occupation_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string RegisterForm_Placeholder_Password_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Placeholder_Password_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mật khẩu.
        /// </summary>
        internal static string RegisterForm_Placeholder_Password_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Placeholder_Password_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number.
        /// </summary>
        internal static string RegisterForm_Placeholder_Phone_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Placeholder_Phone_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số điện thoại.
        /// </summary>
        internal static string RegisterForm_Placeholder_Phone_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Placeholder_Phone_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing up....
        /// </summary>
        internal static string RegisterForm_SigningUp_EN {
            get {
                return ResourceManager.GetString("RegisterForm_SigningUp_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang đăng ký....
        /// </summary>
        internal static string RegisterForm_SigningUp_VI {
            get {
                return ResourceManager.GetString("RegisterForm_SigningUp_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To GestPipe.
        /// </summary>
        internal static string RegisterForm_Title_EN {
            get {
                return ResourceManager.GetString("RegisterForm_Title_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng đến GestPipe.
        /// </summary>
        internal static string RegisterForm_Title_VI {
            get {
                return ResourceManager.GetString("RegisterForm_Title_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Title_Error_EN {
            get {
                return ResourceManager.GetString("Title_Error_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        internal static string Title_Error_VI {
            get {
                return ResourceManager.GetString("Title_Error_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Title_Success_EN {
            get {
                return ResourceManager.GetString("Title_Success_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        internal static string Title_Success_VI {
            get {
                return ResourceManager.GetString("Title_Success_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is required.
        /// </summary>
        internal static string Validation_ConfirmPasswordRequired_EN {
            get {
                return ResourceManager.GetString("Validation_ConfirmPasswordRequired_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu là bắt buộc.
        /// </summary>
        internal static string Validation_ConfirmPasswordRequired_VI {
            get {
                return ResourceManager.GetString("Validation_ConfirmPasswordRequired_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string Validation_EmailRequired_EN {
            get {
                return ResourceManager.GetString("Validation_EmailRequired_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email là bắt buộc.
        /// </summary>
        internal static string Validation_EmailRequired_VI {
            get {
                return ResourceManager.GetString("Validation_EmailRequired_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required.
        /// </summary>
        internal static string Validation_FullNameRequired_EN {
            get {
                return ResourceManager.GetString("Validation_FullNameRequired_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên là bắt buộc.
        /// </summary>
        internal static string Validation_FullNameRequired_VI {
            get {
                return ResourceManager.GetString("Validation_FullNameRequired_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email.
        /// </summary>
        internal static string Validation_InvalidEmail_EN {
            get {
                return ResourceManager.GetString("Validation_InvalidEmail_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập email hợp lệ.
        /// </summary>
        internal static string Validation_InvalidEmail_VI {
            get {
                return ResourceManager.GetString("Validation_InvalidEmail_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string Validation_PasswordMismatch_EN {
            get {
                return ResourceManager.GetString("Validation_PasswordMismatch_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu xác nhận không khớp.
        /// </summary>
        internal static string Validation_PasswordMismatch_VI {
            get {
                return ResourceManager.GetString("Validation_PasswordMismatch_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string Validation_PasswordRequired_EN {
            get {
                return ResourceManager.GetString("Validation_PasswordRequired_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu là bắt buộc.
        /// </summary>
        internal static string Validation_PasswordRequired_VI {
            get {
                return ResourceManager.GetString("Validation_PasswordRequired_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters.
        /// </summary>
        internal static string Validation_PasswordTooShort_EN {
            get {
                return ResourceManager.GetString("Validation_PasswordTooShort_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu tối thiểu 6 ký tự.
        /// </summary>
        internal static string Validation_PasswordTooShort_VI {
            get {
                return ResourceManager.GetString("Validation_PasswordTooShort_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be 10–11 digits.
        /// </summary>
        internal static string Validation_Phone10Digits_EN {
            get {
                return ResourceManager.GetString("Validation_Phone10Digits_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại phải có 10–11 chữ số.
        /// </summary>
        internal static string Validation_Phone10Digits_VI {
            get {
                return ResourceManager.GetString("Validation_Phone10Digits_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must contain only digits.
        /// </summary>
        internal static string Validation_PhoneOnlyDigits_EN {
            get {
                return ResourceManager.GetString("Validation_PhoneOnlyDigits_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại chỉ được chứa chữ số.
        /// </summary>
        internal static string Validation_PhoneOnlyDigits_VI {
            get {
                return ResourceManager.GetString("Validation_PhoneOnlyDigits_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must start with 0.
        /// </summary>
        internal static string Validation_PhoneStartWith0_EN {
            get {
                return ResourceManager.GetString("Validation_PhoneStartWith0_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại phải bắt đầu bằng 0.
        /// </summary>
        internal static string Validation_PhoneStartWith0_VI {
            get {
                return ResourceManager.GetString("Validation_PhoneStartWith0_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Province/City.
        /// </summary>
        internal static string Validation_SelectAddress_EN {
            get {
                return ResourceManager.GetString("Validation_SelectAddress_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn Tỉnh/Thành phố.
        /// </summary>
        internal static string Validation_SelectAddress_VI {
            get {
                return ResourceManager.GetString("Validation_SelectAddress_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select educational level.
        /// </summary>
        internal static string Validation_SelectEdu_EN {
            get {
                return ResourceManager.GetString("Validation_SelectEdu_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn trình độ học vấn.
        /// </summary>
        internal static string Validation_SelectEdu_VI {
            get {
                return ResourceManager.GetString("Validation_SelectEdu_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select gender.
        /// </summary>
        internal static string Validation_SelectGender_EN {
            get {
                return ResourceManager.GetString("Validation_SelectGender_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn giới tính.
        /// </summary>
        internal static string Validation_SelectGender_VI {
            get {
                return ResourceManager.GetString("Validation_SelectGender_VI", resourceCulture);
            }
        }
    }
}
