//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestPipePowerPonit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestPipePowerPonit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Banner {
            get {
                object obj = ResourceManager.GetObject("Banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bottom_to_top {
            get {
                object obj = ResourceManager.GetObject("Bottom_to_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse File....
        /// </summary>
        public static string Btn_Browse {
            get {
                return ResourceManager.GetString("Btn_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Gesture.
        /// </summary>
        public static string Btn_CustomGesture {
            get {
                return ResourceManager.GetString("Btn_CustomGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesture Control.
        /// </summary>
        public static string Btn_GestureControl {
            get {
                return ResourceManager.GetString("Btn_GestureControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Btn_Home {
            get {
                return ResourceManager.GetString("Btn_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        public static string Btn_Instruction {
            get {
                return ResourceManager.GetString("Btn_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation.
        /// </summary>
        public static string Btn_Present {
            get {
                return ResourceManager.GetString("Btn_Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Show.
        /// </summary>
        public static string Btn_SlideShow {
            get {
                return ResourceManager.GetString("Btn_SlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Btn_Training {
            get {
                return ResourceManager.GetString("Btn_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Btn_Version {
            get {
                return ResourceManager.GetString("Btn_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clenchedImg {
            get {
                object obj = ResourceManager.GetObject("clenchedImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clenchLeftImg {
            get {
                object obj = ResourceManager.GetObject("clenchLeftImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string Col_Accuracy {
            get {
                return ResourceManager.GetString("Col_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string Col_LastUpdate {
            get {
                return ResourceManager.GetString("Col_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesture Name.
        /// </summary>
        public static string Col_Name {
            get {
                return ResourceManager.GetString("Col_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Col_Status {
            get {
                return ResourceManager.GetString("Col_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesture Type.
        /// </summary>
        public static string Col_Type {
            get {
                return ResourceManager.GetString("Col_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CustomCamera {
            get {
                object obj = ResourceManager.GetObject("CustomCamera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap English {
            get {
                object obj = ResourceManager.GetObject("English", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap eye {
            get {
                object obj = ResourceManager.GetObject("eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Gender_Other {
            get {
                return ResourceManager.GetString("Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap google {
            get {
                object obj = ResourceManager.GetObject("google", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap handlestaticImg {
            get {
                object obj = ResourceManager.GetObject("handlestaticImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Home_Welcome {
            get {
                return ResourceManager.GetString("Home_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_add {
            get {
                object obj = ResourceManager.GetObject("icon_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_bell {
            get {
                object obj = ResourceManager.GetObject("icon_bell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_down_arrow {
            get {
                object obj = ResourceManager.GetObject("icon_down_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_gesture {
            get {
                object obj = ResourceManager.GetObject("icon_gesture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_home {
            get {
                object obj = ResourceManager.GetObject("icon_home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_home_fake {
            get {
                object obj = ResourceManager.GetObject("icon_home_fake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_instruction {
            get {
                object obj = ResourceManager.GetObject("icon_instruction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_logout {
            get {
                object obj = ResourceManager.GetObject("icon_logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_present {
            get {
                object obj = ResourceManager.GetObject("icon_present", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_search {
            get {
                object obj = ResourceManager.GetObject("icon_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_training {
            get {
                object obj = ResourceManager.GetObject("icon_training", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_traininggesture {
            get {
                object obj = ResourceManager.GetObject("icon_traininggesture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_user {
            get {
                object obj = ResourceManager.GetObject("icon_user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_version {
            get {
                object obj = ResourceManager.GetObject("icon_version", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_view {
            get {
                object obj = ResourceManager.GetObject("icon_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap indexImg {
            get {
                object obj = ResourceManager.GetObject("indexImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string Lbl_Accuracy {
            get {
                return ResourceManager.GetString("Lbl_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Presentation Category:.
        /// </summary>
        public static string Lbl_Category {
            get {
                return ResourceManager.GetString("Lbl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Result.
        /// </summary>
        public static string Lbl_LastResult {
            get {
                return ResourceManager.GetString("Lbl_LastResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pose Target.
        /// </summary>
        public static string Lbl_PoseTarget {
            get {
                return ResourceManager.GetString("Lbl_PoseTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation Camera.
        /// </summary>
        public static string Lbl_PresentationPreview {
            get {
                return ResourceManager.GetString("Lbl_PresentationPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation File.
        /// </summary>
        public static string Lbl_PresentiontationFile {
            get {
                return ResourceManager.GetString("Lbl_PresentiontationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Lbl_Reason {
            get {
                return ResourceManager.GetString("Lbl_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string Lbl_Result_Correct {
            get {
                return ResourceManager.GetString("Lbl_Result_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong.
        /// </summary>
        public static string Lbl_Result_Wrong {
            get {
                return ResourceManager.GetString("Lbl_Result_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Presentation Type:.
        /// </summary>
        public static string Lbl_Topic {
            get {
                return ResourceManager.GetString("Lbl_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training time.
        /// </summary>
        public static string Lbl_TrainingDay {
            get {
                return ResourceManager.GetString("Lbl_TrainingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Result.
        /// </summary>
        public static string Lbl_TrainingResult {
            get {
                return ResourceManager.GetString("Lbl_TrainingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string LblClose {
            get {
                return ResourceManager.GetString("LblClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string LblDirection {
            get {
                return ResourceManager.GetString("LblDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        public static string LblInstruction {
            get {
                return ResourceManager.GetString("LblInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left hand.
        /// </summary>
        public static string LblLeftHand {
            get {
                return ResourceManager.GetString("LblLeftHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string LblNote {
            get {
                return ResourceManager.GetString("LblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File:.
        /// </summary>
        public static string LblOpenFile {
            get {
                return ResourceManager.GetString("LblOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right hand.
        /// </summary>
        public static string LblRightHand {
            get {
                return ResourceManager.GetString("LblRightHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to present now?.
        /// </summary>
        public static string LblSubtitle {
            get {
                return ResourceManager.GetString("LblSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Left_to_right {
            get {
                object obj = ResourceManager.GetObject("Left_to_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change language.
        /// </summary>
        public static string Message_ChangeLanguageFailed {
            get {
                return ResourceManager.GetString("Message_ChangeLanguageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed successfully!.
        /// </summary>
        public static string Message_ChangeLanguageSuccess {
            get {
                return ResourceManager.GetString("Message_ChangeLanguageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load profile..
        /// </summary>
        public static string Message_LoadProfileFailed {
            get {
                return ResourceManager.GetString("Message_LoadProfileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        public static string Message_LogoutConfirm {
            get {
                return ResourceManager.GetString("Message_LogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during logout.
        /// </summary>
        public static string Message_LogoutError {
            get {
                return ResourceManager.GetString("Message_LogoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to logout..
        /// </summary>
        public static string Message_LogoutFailed {
            get {
                return ResourceManager.GetString("Message_LogoutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out successfully!.
        /// </summary>
        public static string Message_LogoutSuccess {
            get {
                return ResourceManager.GetString("Message_LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update profile..
        /// </summary>
        public static string Message_ProfileUpdateFailed {
            get {
                return ResourceManager.GetString("Message_ProfileUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully!.
        /// </summary>
        public static string Message_ProfileUpdateSuccess {
            get {
                return ResourceManager.GetString("Message_ProfileUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap middleImg {
            get {
                object obj = ResourceManager.GetObject("middleImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pinkyImg {
            get {
                object obj = ResourceManager.GetObject("pinkyImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ProfileForm_Address {
            get {
                return ResourceManager.GetString("ProfileForm_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string ProfileForm_BirthDate {
            get {
                return ResourceManager.GetString("ProfileForm_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ProfileForm_BtnBack {
            get {
                return ResourceManager.GetString("ProfileForm_BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ProfileForm_BtnCancel {
            get {
                return ResourceManager.GetString("ProfileForm_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ProfileForm_BtnChangePassword {
            get {
                return ResourceManager.GetString("ProfileForm_BtnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string ProfileForm_BtnEdit {
            get {
                return ResourceManager.GetString("ProfileForm_BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string ProfileForm_BtnSave {
            get {
                return ResourceManager.GetString("ProfileForm_BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string ProfileForm_Company {
            get {
                return ResourceManager.GetString("ProfileForm_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Level.
        /// </summary>
        public static string ProfileForm_Education {
            get {
                return ResourceManager.GetString("ProfileForm_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ProfileForm_Email {
            get {
                return ResourceManager.GetString("ProfileForm_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string ProfileForm_FullName {
            get {
                return ResourceManager.GetString("ProfileForm_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string ProfileForm_Gender {
            get {
                return ResourceManager.GetString("ProfileForm_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading profile....
        /// </summary>
        public static string ProfileForm_Loading {
            get {
                return ResourceManager.GetString("ProfileForm_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string ProfileForm_Occupation {
            get {
                return ResourceManager.GetString("ProfileForm_Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string ProfileForm_Phone {
            get {
                return ResourceManager.GetString("ProfileForm_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string ProfileForm_Saving {
            get {
                return ResourceManager.GetString("ProfileForm_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string ProfileForm_Title {
            get {
                return ResourceManager.GetString("ProfileForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data.
        /// </summary>
        public static string Reason_InsufficientData {
            get {
                return ResourceManager.GetString("Reason_InsufficientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low confidence.
        /// </summary>
        public static string Reason_LowConfidence {
            get {
                return ResourceManager.GetString("Reason_LowConfidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ML error.
        /// </summary>
        public static string Reason_MLError {
            get {
                return ResourceManager.GetString("Reason_MLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion processing failed.
        /// </summary>
        public static string Reason_MotionProcessingFailed {
            get {
                return ResourceManager.GetString("Reason_MotionProcessingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement too small.
        /// </summary>
        public static string Reason_MotionSmall {
            get {
                return ResourceManager.GetString("Reason_MotionSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration too short.
        /// </summary>
        public static string Reason_StaticDuration {
            get {
                return ResourceManager.GetString("Reason_StaticDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still moving (not static enough).
        /// </summary>
        public static string Reason_StaticMotion {
            get {
                return ResourceManager.GetString("Reason_StaticMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too fast.
        /// </summary>
        public static string Reason_TooFast {
            get {
                return ResourceManager.GetString("Reason_TooFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong axis of movement.
        /// </summary>
        public static string Reason_WrongAxis {
            get {
                return ResourceManager.GetString("Reason_WrongAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong movement direction.
        /// </summary>
        public static string Reason_WrongDirection {
            get {
                return ResourceManager.GetString("Reason_WrongDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Right_to_left {
            get {
                object obj = ResourceManager.GetObject("Right_to_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ringImg {
            get {
                object obj = ResourceManager.GetObject("ringImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap thumbImg {
            get {
                object obj = ResourceManager.GetObject("thumbImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Title_Confirmation {
            get {
                return ResourceManager.GetString("Title_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string Title_ConnectionError {
            get {
                return ResourceManager.GetString("Title_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Title_Success {
            get {
                return ResourceManager.GetString("Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Top_to_bottom {
            get {
                object obj = ResourceManager.GetObject("Top_to_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Vietnamese {
            get {
                object obj = ResourceManager.GetObject("Vietnamese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
